spring:
  application:
    name: chatbot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_ENDPOINT}
    username: root
    password: ${MYSQL}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  expiration_time: 3600

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      auto: false
    stack:
      auto: false

llm:
  server:
    url: ${LLM_SERVER_URL}